service: mhdb

package:
  exclude:
    - node_modules/.cache/**
    - package.json
    - package-lock.json
    - .cache
    - __tests__/
    - .vscode
    - .DS_Store
    - coverage
    - src
  include:
    - dist

plugins:
  - serverless-offline
  - serverless-apigw-binary

custom:
  serverless-offline:
    port: 8000
    dontPrintOutput: true
  apigwBinary:
    types:
      - '*/*'

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 256
  timeout: 15
  environment:
    NODE_ENV: production

functions:
  index:
    handler: lambda/dist.handler
    events:
      - http:
          path: /dist/{proxy+}
          method: GET
  search:
    handler: lambda/search.handler
    events:
      - http:
          path: /search
          method: GET
          cors: true

resources:
  Description: Modern Haiku Database
